name: "SCA sbom generation"
description: "Generate a Software Bill of Materials(sbom) for a given repository"
author: "Kaushik Vaida"
inputs:
  repo_url:
    description: 'The Repository URL to generate an sbom'
    required: false
    default: '${{ github.event.repository.url }}'
  repo_name:
    description: 'The name of the repository'
    required: false
    default: '${{ github.event.repository.name }}'
  dtrack_api_key:
    description: "The API key for dtrack"
    required: false
    default: ''
  output:
    description: ''
outputs:
  output: 
    description: "output of task"
runs:
  using: "docker"
  image: "Dockerfile"
